//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristsGo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public Nullable<int> IdTour { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<System.DateTime> DateDeparture { get; set; }
        public Nullable<System.DateTime> DateArrival { get; set; }
        public Nullable<System.DateTime> DateBooking { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Tours Tours { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
