//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristsGo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int IdBooking { get; set; }
        public string Requesites { get; set; }
        public Nullable<int> Promocode { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Promocode Promocode1 { get; set; }
    }
}
